FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy all necessary files there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

# Copy config files and assets
COPY config/ $DAGSTER_HOME/config/
COPY assets/ $DAGSTER_HOME/assets/

WORKDIR $DAGSTER_HOME
